// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.171013.2

#pragma once

#include "module.h"
#include "winrt/Windows.Foundation.h"
#include "winrt/Component.h"

namespace winrt::Component::implementation {

template <typename D, typename ... I>
struct WINRT_EBO Button_base : impl::module_lock, implements<D, Component::IButton, Component::IButton2, Windows::Foundation::IStringable, I ...>
{
    using class_type = Component::Button;
    
    operator class_type() const noexcept
    {
        static_assert(std::is_same_v<typename D::first_interface, impl::default_interface_t<class_type>>);
        class_type result{ nullptr };
        attach_abi(result, detach_abi(static_cast<impl::default_interface_t<class_type>>(*this)));
        return result;
    }

    hstring GetRuntimeClassName() const
    {
        return L"Component.Button";
    }
};

}

namespace winrt::Component::factory_implementation {

template <typename D, typename T, typename ... I>
struct WINRT_EBO ButtonT : impl::module_lock, implements<D, Windows::Foundation::IActivationFactory, I ...>
{
    hstring GetRuntimeClassName() const
    {
        return L"Component.Button";
    }

    Windows::Foundation::IInspectable ActivateInstance() const
    {
        return make<T>();
    }
};

}

#if defined(WINRT_FORCE_INCLUDE_BUTTON_XAML_G_H) || __has_include("Button.xaml.g.h")

#include "Button.xaml.g.h"

#else

namespace winrt::Component::implementation
{
    template <typename D, typename ... I>
    using ButtonT = Button_base<D, I ...>;
}

#endif
