// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.170906.1

#pragma once

#include "module.h"

namespace winrt::Component::implementation {

template <typename D, typename ... I>
struct Button_base : impl::module_lock, implements<D, Component::IButton, Component::IButton2, Windows::Foundation::IStringable, I ...>
{
    using class_type = Component::Button;

    operator class_type() const noexcept
    {
        class_type result{ nullptr };
        attach_abi(result, detach_abi(static_cast<typename D::first_interface>(*this)));
        return result;
    }

    hstring GetRuntimeClassName() const
    {
        return L"Component.Button";
    }
};

}

namespace winrt::Component::factory_implementation {

template <typename D, typename T, typename ... I>
struct ButtonT : impl::module_lock, implements<D, Windows::Foundation::IActivationFactory, I ...>
{
    hstring GetRuntimeClassName() const
    {
        return L"Component.Button";
    }

    Windows::Foundation::IInspectable ActivateInstance() const
    {
        return make<T>();
    }
};

}

#pragma warning(suppress: 4067)
#if defined(WINRT_FORCE_INCLUDE_BUTTON_XAML_G_H) || __has_include("Button.xaml.g.h")

#include "Button.xaml.g.h"

#else

namespace winrt::Component::implementation
{
    template <typename D, typename ... I>
    using ButtonT = Button_base<D, I ...>;
}

#endif
