// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.171013.2

#include "pch.h"
#include "Button.h"

namespace winrt::impl
{
    namespace
    {
        std::atomic<uint32_t> s_module_lock{};
    }

    module_lock::module_lock()
    {
        ++s_module_lock;
    }

    module_lock::~module_lock()
    {
        --s_module_lock;
    }
}

using namespace winrt;

HRESULT __stdcall DllCanUnloadNow()
{
    if (impl::s_module_lock)
    {
        return S_FALSE;
    }

    clear_factory_cache();
    return S_OK;
}

HRESULT __stdcall DllGetActivationFactory(HSTRING classId, ::IUnknown** factory)
{
    try
    {
        wchar_t const* const name = WindowsGetStringRawBuffer(classId, nullptr);

        if (0 == wcscmp(name, L"Component.Button"))
        {
            *factory = detach_abi(make<Component::factory_implementation::Button>());
            return S_OK;
        }

        *factory = nullptr;
        return hresult_class_not_available().to_abi();
    }
    catch (...)
    {
        *factory = nullptr;
        return impl::to_hresult();
    }
}
